// export const IMAGES = [
//     {
//         src:'images/elegant-woman.png',
//         alt:'elegant-woman',
//         nombre:'Ale',
//         edad: 25, 
//         poder:'5',
//     },
//     {
//         src:'/images/excited-white-girl.png',
//         alt:'excited-white-girl-bright',
//         nombre:'Mia',
//         edad: 26,
//         poder:'1'
//     },
//     {
//         src:'/images/pexels-dima-valkov-1.png', 
//         alt:'pexels-dima-valkov',
//         nombre:'Lore',
//         edad: 27,
//         poder:'2',
//     },
//     {
//         src:'/images/pexels-dima-valkov-2.png',
//         alt:'pexels-dima-valkov2',
//         nombre:'Caro',
//         edad: 28,
//         poder:'3',
//     },
//     { 
//         src:'/images/pexels-dima-valkov-3.png',
//         alt:'pexels-dima-valkov3',
//         nombre:'Luli',
//         edad: 29,
//         poder:'4',
//     },
//     { 
//         src:'/images/pexels-dima-valkov-3.png',
//         alt:'pexels-dima-valkov3',
//         nombre:'Luli',
//         edad: 29,
//         poder:'4',
//     },
// ]
export const IMAGES = [
{
    title:'Batman:The Movie(1966)',
    anio:1966,
    reparto:'Adam West, Burt Ward, Cesar Romero.',
    director:'Leslie H. Martinson',
    duracion:'105 minutos',
    dondeVer:'Consulta servicios de alquiler de películas en línea o bibliotecas locales.',
    src:'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.rottentomatoes.com%2Fm%2Fbatman_the_movie&psig=AOvVaw2vCCQV-RpTnOZOWB2kg3hD&ust=1717857535232000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMDnyZbcyYYDFQAAAAAdAAAAABAE',
    temaPrincipaldelaBandaSonora:'"Batman Theme" por Neal Hefti',
    compositordelaBandaSonora:'Neal Hefti',
    premios:'Ganadora de un Oscar al Mejor Diseño de Vestuario.',
    alt:'Batman: The Movie (1966)' 
},
{
    title:'Batman(1989)',
    anio:1989,
    reparto:'Michael Keaton, Jack Nicholson, Kim Basinger.',
    director:'Tim Burton.',
    duracion:'126 minutos.',
    dondeVer:'Disponible en servicios de streaming como Amazon Prime Video.',
    src:'https://play-lh.googleusercontent.com/TN8XVW54-ePBPhkKNk90994IrC0MxvN1IwkqllSlpxWFqSYR-artGNI4Wufh6wR9XIEUqdMRn9z6WQ4Sag',
    temaPrincipaldelaBandaSonora:'"Batdance" por Prince',
    compositordelaBandaSonora:'Danny Elfman.',
    premios:'Ganadora de un Oscar al Mejor Diseño de Escenografía.',
    alt:'Batman (1989).'
},
{
    title:'Batman Begins(2005)',
    anio:2005,
    reparto:'Christian Bale, Michael Caine, Liam Neeson',
    director:'Christopher Nolan',
    duracion:'140 minutos',
    dondeVer:'Disponible en servicios de streaming como Amazon Prime Video',
    src:'https://pics.filmaffinity.com/Batman_Begins-352424097-large.jpg',
    temaPrincipaldelaBandaSonora:'"Vespertilio" por Hans Zimmer',
    compositordelaBandaSonora:'Hans Zimmer',
    premios:' Ganadora de un Premio Oscar al Mejor Actor de Reparto (Heath Ledger)',
    alt:'Batman Begins (2005)'
},
{
    title:'The Dark Knight Rises(2012)',
    anio:2012,
    reparto:' Christian Bale, Tom Hardy, Anne Hathaway.',
    director:'Christopher Nolan',
    duracion:'165 minutos',
    dondeVer:'Puedes buscar en servicios de streaming como Amazon Prime Video.',
    src:'https://www.originalfilmart.com/cdn/shop/products/dark_knight_rises_2012_quad_original_film_art.jpg?v=1607205303',
    temaPrincipaldelaBandaSonora:'"Rise" por Hans Zimmer',
    compositordelaBandaSonora:'Hans Zimmer',
    premios:' Ganadora de varios premios técnicos.',
    alt:'The Dark Knight Rises (2012)'
},
{
    title:'The Batman(2022)',
    anio:2022,
    reparto:'Robert Pattinson, Zoë Kravitz, Paul Dano.',
    director:'Matt Reeves',
    duracion:'176 minutos',
    dondeVer:'Puedes buscar en servicios de streaming como Amazon Prime Video.',
    src:'https://pics.filmaffinity.com/The_Batman-449856406-large.jpg',
    temaPrincipaldelaBandaSonora:'Michael Giacchino',
    compositordelaBandaSonora:'Michael Giacchino',
    premios:'🦇',
    alt:'The Batman (2022)'
},
]